export const CATEGORY_IDS = [
  "construction_trades",
  "manufacturing_fabrication",
  "retail_storefront",
  "hospitality_food_service",
  "real_estate_property",
  "auto_transportation",
  "professional_admin_services",
  "events_entertainment",
  "healthcare_personal_services",
  "education_childcare",
  "technology_telecom",
  "nonprofits_community",
  "agriculture_environmental",
  "marine_watercraft",
] as const;

export type CategoryId = (typeof CATEGORY_IDS)[number];

export const OTHER_VALUE = "other" as const;

export const LOB_MAP: Record<CategoryId, string[]> = {
  construction_trades: [
    "general_contractor",
    "residential_contractor",
    "commercial_contractor",
    "electrician",
    "plumber",
    "hvac_contractor",
    "roofer",
    "mason_concrete_contractor",
    "framing_contractor",
    "drywall_contractor",
    "flooring_installer",
    "painter",
    "carpenter_finish_trim",
    "glazing_window_door_installer",
    "fence_installer",
    "pool_builder_contractor",
    "landscaper_lawn_service",
    "tree_trimming_service",
    "handyman_service",
    "marine_contractor_dock_builder",
    "solar_panel_installer",
    "paving_asphalt_contractor",
    "demolition_contractor",
    "crane_operator_non_owned_equipment",
  ],

  manufacturing_fabrication: [
    "metal_fabrication_shop",
    "plastics_manufacturing",
    "boat_yacht_builder",
    "furniture_manufacturer",
    "electronics_manufacturer",
    "apparel_textile_manufacturer",
    "food_beverage_manufacturer",
  ],

  retail_storefront: [
    "grocery_store_supermarket",
    "convenience_store",
    "liquor_store",
    "clothing_boutique_store",
    "shoe_store",
    "jewelry_store",
    "furniture_store",
    "appliance_store",
    "auto_parts_store",
    "vape_tobacco_shop",
    "marine_supply_store",
    "hardware_store",
  ],

  hospitality_food_service: [
    "restaurant_full_service",
    "restaurant_fast_casual_fast_food",
    "cafe_coffee_shop",
    "bakery",
    "catering_company",
    "food_truck",
    "bar_tavern",
    "nightclub_lounge",
    "hotel_motel",
    "resort",
    "bed_breakfast_inn",
    "short_term_rental_operator",
  ],

  real_estate_property: [
    "residential_property_manager",
    "commercial_property_manager",
    "apartment_building_owner_landlord",
    "shopping_center_plaza_owner",
    "office_building_owner",
    "warehouse_industrial_property_owner",
    "self_storage_facility",
    "hoa_condominium_association",
    "real_estate_investment_firm",
  ],

  auto_transportation: [
    "auto_dealer_new",
    "auto_dealer_used",
    "auto_repair_shop",
    "auto_body_collision_shop",
    "tire_shop",
    "mobile_mechanic",
    "tow_truck_company",
    "trucking_company_motor_carrier",
    "courier_delivery_service",
    "non_emergency_medical_transportation",
    "driving_school",
  ],

  professional_admin_services: [
    "accounting_firm_cpa",
    "consulting_firm",
    "insurance_agency_broker",
    "real_estate_agency",
    "law_firm",
    "marketing_advertising_agency",
    "staffing_employment_agency",
    "notary_service",
    "property_inspection_company",
  ],

  events_entertainment: [
    "event_planner_coordinator",
    "wedding_planner",
    "dj_entertainment_company",
    "banquet_hall_event_venue",
    "trade_show_expo_organizer",
    "festival_fair_organizer",
    "sports_league_tournament_organizer",
    "theater_performing_arts_venue",
    "boat_show_organizer",
  ],

  healthcare_personal_services: [
    "medical_clinic_doctors_office",
    "dentist_office",
    "chiropractic_clinic",
    "physical_therapy_clinic",
    "home_health_care_agency",
    "massage_therapy_clinic",
    "gym_fitness_center",
    "yoga_pilates_studio",
    "beauty_hair_salon",
    "barbershop",
    "nail_salon",
    "tattoo_piercing_studio",
    "spa_med_spa",
  ],

  education_childcare: [
    "daycare_center",
    "preschool",
    "private_school",
    "tutoring_center",
    "after_school_program",
    "summer_camp_day_or_overnight",
    "vocational_trade_school",
  ],

  technology_telecom: [
    "it_consulting_firm",
    "software_development_company",
    "managed_service_provider_msp",
    "data_center_server_hosting",
    "security_alarm_installation_company",
    "telecom_installation_contractor",
  ],

  nonprofits_community: [
    "church_religious_organization",
    "charitable_foundation",
    "community_center",
    "youth_organization_club",
    "advocacy_support_organization",
  ],

  agriculture_environmental: [
    "farm_ranch_operation",
    "crop_producer",
    "irrigation_contractor",
    "pest_control_company",
    "environmental_consulting_firm",
    "landscaping_nursery_garden_center",
  ],

  marine_watercraft: [
    "marina_dockage_facility",
    "boatyard_marine_repair_facility",
    "marine_mechanic_mobile_or_shop",
    "boat_detailing_company",
    "boat_yacht_broker",
    "boat_rental_company",
    "jet_ski_pwc_rental_company",
    "charter_boat_operator",
    "marine_towing_salvage_company",
    "marine_fueling_dock_fuel_service",
  ],
};
